# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: beta-xcode6.3
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
set -o pipefail && xcodebuild test -workspace Example/DNFlyingBadges.xcworkspace -scheme DNFlyingBadges-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
